// TypeScript setup can be done in two ways: global or project-wise

// Global install (using -g flag):
// npm install -g typescript

// Project-wise setup:
// npm init -y               -> creates package.json
// npm install -D typescript -> adds TypeScript as a dev dependency
//                              (creates node_modules & package-lock.json)

// npx tsc --init            -> creates tsconfig.json
//                              (used to configure rootDir and outDir)

// npx tsc                   -> compiles TypeScript files
//                              and generates JavaScript files inside the dist folder

// Folder structure:
// src  -> contains TypeScript (.ts) source files
// dist -> contains compiled JavaScript (.js) files generated by tsc


//if i want to run in node i usw node dist/intro.js

// Optional: Add a start script in package.json to simplify running

// package.json
/*
"scripts": {
  "build": "tsc",
  "start": "node dist/intro.js"
}
*/

// Now you can run:
// npm run build   → Compiles TypeScript
// npm start       → Runs the compiled JavaScript file


function greet(person: string): string {
  return `Hello ${person} welcome to ts`;
}

const userName: string = "Prathmesh";

console.log(greet(userName));





